### PR TITLE
Added Brick gh-repo and alphabetically sorted repository list!

### PR DESCRIPTION
**Pull request by sayak-sarkar**
Added the Brick repository to the list and alphabetically sorted the repository list for better manual lookup and later reference.

### CODE REVIEW

**Comment by debloper** [comment]
Last element of the list/array shouldn't have trailing comma.

**Comment by grssam** [comment]
It actually should have. This reduces the diff size while adding new entries. As in, the person does not have to touch existing code to add new code.

**Comment by grssam** [comment]
And @sayak-sarkar , while you are sorting the array, can you make sure that the same coding standards are followed as written on top of users.json file ?

**Comment by sayak-sarkar** [comment]
@scrapmac Please do check the current `git-repos.json` file and compare it with the proposed sorted file, I think I've abided by as much coding standards as is possible for a simple json file, the present `git-repos.json` however, fails to confirm to the said coding standards with uneven spacing. I've tried to get rid of this un-uniformity before making the commits. For my first commit, I had kept the trailing commas throughout, however removed the last trailing comma post @debloper's comment. Let me know If I should re-introduce it.

**Comment by grssam** [comment]
Yeah, I think you should restart from scratch, make one commit adding the repos you proposed here, and the next commit sorting things, adding missing spaces after "," , maybe copy over the coding style comment from users.json too, and abide that.

**Comment by debloper** [comment]
I agree on the increased DIFF size without the last trailing comma, however I don't thing a _hacky_ list of missing/null last element is a solution to that.

What I generally do in these kinda situations is:

```
var list = [
    item0
,   item1
,   item2
];
```

I think we can use it in this case. As it's almost FUBARing the file anyway for dictionary sorting, I think the leading comma won't do any hamper in DIFF size for this one commit - and from next on it's best of both world.

So my suggestion to @sayak-sarkar:
0. `rm -rf` working directory, delete personal fork.
1. Refork the repository & clone it
2. [Commit 1] `mv git-repos.json ../` & don't change any content in git-repos.json file (it should be parallel to users.json). You will have to change the script src in index.html though.
3. [Commit 2] Make the dictionary sorting of existing repositories
4. [Commit 3] Add new Mozilla Repositories as you see fit & in the commit message, put "fixes #44" at the end

That's about it, I guess.

**Comment by grssam** [comment]
@debloper I think we should be consistent with coding style across this repo. Most of us are inclined towards Mozilla style of coding. (basically what I have commented in users.json at the top). About trailing comma creating missing/null element. It does not. trailing comma has absolutely no effect in JS.
About the step 3 [commit 2] I think addition of the new repo should be a separate commit than sorting of the file so as to make it clear which repo got added while looking through history of commits.

**Comment by debloper** [comment]
I don't deny that we need to be consistent, but I do see some inconsistencies in those proposals (e.g. proposals for consistency in first-review-then-merge, overlooking the consistency of the list-jsons needing to be in repo-root for easy accessibility & community hacking - and then breaking it without asking others etc.). Moreover, the repo needs a consistent style, it doesn't yet have one - and it's not too late to have one.

If a better consistency is found, then any orthodoxy to stick to the prior one is illogical. Whatever is previously written, or whatever is Mozilla WebDev team following doesn't mean that we can't do better. Leading comma is new-ish, it's better (and doesn't create the debate whether it has any effect in JS or not). _Although, I do need to study about the effect of trailing comma in JS - one convention was it used to break in IE (which, I know, isn't a very strong reason), I'm yet to know its other effects, if any._

Meanwhile, good suggestion on the **additional commit to add new repos**. Updated my previous comment with that.

**Comment by grssam** [comment]
Did you browse the js files first ? Every JS file has the same coding style. It will have by default, because both me and Sankha are used to one particular JS format style and we only wrote all the JS files. That us why, let is simply go by whatever is written in the comment section of `users.json` file.

About the trailing comma breaking IE. That is in an object, not in an Array. That too only till IE 8.

I think you still did not get the proposal of first-review-then-merge . So let me take this comment to explain it in detail:
- When an external person sends a PR, then one of the internal person can review it and merge it. This time, the reviewer and merger can be the same person as the code change is done by some external person.
- When an internal person sends a PR, then it needs to be r+'ed by someone internal other than him. After he gets an r+, anyone including him can merge it.

`Here external means someone who is not part of the organization MozillaIndia (i.e. someone other than @debloper , @sankha93  and me). Internal means just the opposite.`

The whole point here is that the one who wrote the code in an PR should not merge it without anyone from the three of us, except that person, reviewing it first.

**Comment by debloper** [comment]
Thanks for making it clear. Now we're discussing something important, but something completely off-topic from the main issue. _And it sounds like we're fighting over a same girl._

I agree on the IE8's misbehave with objects with trailing comma, I didn't realize we're not gonna do the same for Objects in this (so I didn't differentiate on that note - as the base point was increased DIFF size, which applies to both). Also, thanks for making the review proposal clear. Too bad it has to hang in here as a offtopic :P

Let's retire the discussion from here as on the pull-request we both agree.

**Comment by grssam** [comment]
So I think its decided ;) @sayak-sarkar Please go on with the coding styling I explained and the commit steps in https://github.com/MozillaIndia/leaderboard/pull/44#issuecomment-23403164 .

**Comment by grssam** [comment]
@sayak-sarkar I know it has been a hard one :( . But are you still up for the changes mentioned ?

**Pull request closed without merging**
