### PR TITLE
fixes #36

### LINKED ISSUE #36: Give a link to BMO user-profile page
The https://bugzilla.mozilla.org/user_profile?login=username%40email.tld can provide some more\* useful insights about one's BMO activities.

> Especially if someone is involved more with locked/private bugs.

### PR DESCRIPTION
**Pull request by chetandhembre**

### CODE REVIEW

**Comment by grssam** [comment]
Thanks for taking this up Chetan.
r-
See the comments in your commit.

<Note to all: this is to be kept on hold until server-side transfer is complete>

**Comment by debloper** [comment]
Hey Chetan, the typo in the filename is kinda awkward as well, ans so is the capitalization.
I'd rather suggest, till our JS files get too long to manage, we try to fragment the code less in many files - so it's totally cool to define/pre-hoist the constants in the main controller JS file itself (to reduce the HTTP requests).

You should be able to work on the repo, on other issues - but before taking up a bug to fix, please let us know. Not all the issues need to be fixed. There are certain NOTABUG, WORKSFORME or OBSOLETE issues.

Meanwhile, a quick poke to @sankha93 to keep the serverside code updated in a different branch - so that people can know what's going on.

**Comment by chetandhembre** [comment]
Sorry about typo mistake .. i missed that .. ok i will remove constans.js
file. And Can someone tell which bug are need to fixed ?

**Comment by debloper** [comment]
It'll be best to clobber the repo & start anew - too many odd/awkward commits - isn't it?

**Comment by chetandhembre** [comment]
sure

**Pull request closed without merging**
