### PR TITLE
Containerized Mozillians Leaderboard frontend using docker 

### PR DESCRIPTION
**Pull request by kmehant**
I have containerized leaderboard front-end using Docker. Nginx web server is used to serve the static files at localhost.
Run this command in the git repo to serve the site at localhost.
`docker-compose up`

### CODE REVIEW

**Comment by asdofindia** [comment]
This repo isn't even being used.

**Comment by kmehant** [comment]
> This repo isn't even being used.

Yes! I have seen it just now! The commits way too old.

**Comment by kmehant** [comment]
> This repo isn't even being used.

@asdofindia 
Is the backend being used or complete leaderboard feature is not being used?

**Comment by kmehant** [comment]
> This repo isn't even being used.

@asdofindia 
I am closing it as it is no longer being used or maintained

**Comment by debloper** [comment]
@kmehant sorry for the late response, and thanks for trying to help.

As it stands (since late 2013), the way we were pulling the data (see @MozillaIndia/leaderchalk) was by checking nationality of contributors from Mozillians' API which has been discontinued due to data privacy policies from 3rd party consumption (iirc, CORS only validation, only works for `*.mozilla.org` domains now). We could refactor the code to make it use JSONP instead of AJAX to get around that. But nobody got the time or energy to do that. If you're willing to make that happen, I'll be glad to answer your questions. Once that blocker is out of the way, this PR will probably have some actual purpose.

Cheers!

**Pull request closed without merging**
